### PR TITLE
switch backends from JSON to JSON::MaybeXS

### PR DESCRIPTION
**Pull request by karenetheridge**
I can't figure out where the json text actually comes from, but that's irrelevant for this change :)

### CODE REVIEW

**Comment by neilbowers** [comment]
What's my motive for switch to use this?

Given JSON will use XS if it's available. Oh, hold on though, I've just seen in the JSON doc:

> This version is compatible with JSON::XS 2.34 and later. (Not yet compatble to JSON::XS 3.0x.)

Is that why you created JSON::MaybeXS?

How is this different from AnyMoose, which is now deprecated? :-)

**Comment by karenetheridge** [comment]
JSON.pm only uses JSON::XS when available. JSON::MaybeXS was written to also use the other XS backend(s) whenever possible, which have bug fixes that JSON::XS itself does not have.

And yes, JSON.pm also has some compatibility issues which are being rather slow to get fixed.

I don't understand your comparison to Any::Moose.

**Comment by shadowcat-mst** [comment]
Any::Moose is deprecated because it was the wrong answer to the right question, and Moo was the right answer.

JSON was also the wrong answer to the right question, and JSON::MaybeXS is my attempt to supply an appropriate answer.

**Comment by neilbowers** [comment]
It was more a general question than specifically for this dist, since I have a lot of modules / code doing JSON stuff, as do many of us.

I'll merge this one, but will have a play with JSON modules before I do any more :-)

**Comment by neilbowers** [comment]
Thanks!

**Pull request merged**
