### PR TITLE
Adds ua method for providing your own UserAgent.

### PR DESCRIPTION
**Pull request by oalders**
Also documents previously secret "url" attribute.

I'm working with a local copy of 02packages.details.txt which is created by OrePAN.  HTTP::Tiny won't fetch files and this seems easier than firing up my own Plack server just to be able to read a file.  ;)

I added a workaround for caching, since I was always getting a 200 even when the file hadn't changed.  If you can use this, feel free to bastardize it to your heart's content!

### CODE REVIEW

**Comment by oalders** [comment]
Have you thought any more about this? I need to write a script to diff a local 02packages against the latest on CPAN.  This would have been a good way to go, but with no access to the UA and HTTP::Tiny still not supporting the file scheme, it's basically impossible without subclassing the module and overriding _cache_file_if_needed() which is a pretty terrible solution. ;)

**Comment by neilbowers** [comment]
Sorry for being so tardy -- my merge velocity must be rubbish :-(

**Comment by oalders** [comment]
:+1: To be clear, I wasn't saying _merge this now_, but I was wondering if you had a different solution in mind.  :)

**Comment by neilbowers** [comment]
When you first submitted it, I had various thoughts in mind, but i don't remember what they were, and I'm a bit swamped helping people with suggestions for the PRC, as we approach the end of Jan, so I figured best to merge and let you get on with it.

**Comment by neilbowers** [comment]
Version 0.11 making its way to CPAN as I type...

**Pull request merged**
