### PR TITLE
Cache per uri

### LINKED ISSUE #4: Base the cache name on the path to 02packages
I need to use this module to compare a local 02packages file and one on CPAN.  I'll need both objects in parallel, so I need each to have its own cache file location.  Encoding the URI (file or http) and making that the cache name would solve this.  For example, cpanm does it this way:

```
ls ~/.cpanm/sources/
darkpan                                                   file%Users%olaf%Documents%perl%orepan%orepan-test%darkpan http%backpan.perl.org                                     http%www.cpan.org
file%Users%olaf%Documents%perl%orepan%darkpan             file%darkpan                                              http%cpan.metacpan.org
```

I will send a patch for this if you think it's a good idea.

### PR DESCRIPTION
**Pull request by oalders**
Fixes #4

### CODE REVIEW

**Comment by oalders** [comment]
*crickets*

**Comment by neilbowers** [comment]
Thank you :-)

**Comment by oalders** [comment]
:+1:

**Comment by neilbowers** [comment]
Version 0.12 now making its way to CPAN.

**Pull request merged**
